

//! Autogenerated weights for `pallet_external_validators`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-08-15, STEPS: `2`, REPEAT: `2`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `BM-MBP.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/datahaven-stagenet-runtime/datahaven_stagenet_runtime.compact.compressed.wasm
// --pallet
// pallet_external_validators
// --extrinsic
// 
// --template
// benchmarking/frame-weight-template.hbs
// --output
// runtime/stagenet/src/weights/pallet_external_validators.rs
// --steps
// 2
// --repeat
// 2

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for `pallet_external_validators`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_external_validators::WeightInfo for WeightInfo<T> {
	/// Storage: `ExternalValidators::SkipExternalValidators` (r:0 w:1)
	/// Proof: `ExternalValidators::SkipExternalValidators` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn skip_external_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 2_000_000 picoseconds.
		Weight::from_parts(2_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Session::NextKeys` (r:1 w:0)
	/// Proof: `Session::NextKeys` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `ExternalValidators::WhitelistedValidators` (r:1 w:1)
	/// Proof: `ExternalValidators::WhitelistedValidators` (`max_values`: Some(1), `max_size`: Some(2002), added: 2497, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 99]`.
	fn add_whitelisted(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `538 + b * (25 ±0)`
		//  Estimated: `4003 + b * (26 ±0)`
		// Minimum execution time: 16_000_000 picoseconds.
		Weight::from_parts(16_887_755, 4003)
			// Standard Error: 32_268
			.saturating_add(Weight::from_parts(112_244, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 26).saturating_mul(b.into()))
	}
	/// Storage: `ExternalValidators::WhitelistedValidators` (r:1 w:1)
	/// Proof: `ExternalValidators::WhitelistedValidators` (`max_values`: Some(1), `max_size`: Some(2002), added: 2497, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[1, 100]`.
	fn remove_whitelisted(b: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `215 + b * (20 ±0)`
		//  Estimated: `3487`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(9_434_343, 3487)
			// Standard Error: 20_823
			.saturating_add(Weight::from_parts(65_656, 0).saturating_mul(b.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ExternalValidators::ForceEra` (r:0 w:1)
	/// Proof: `ExternalValidators::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	fn force_era() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 10_000_000 picoseconds.
		Weight::from_parts(12_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `ExternalValidators::ExternalIndex` (r:0 w:1)
	/// Proof: `ExternalValidators::ExternalIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::ExternalValidators` (r:0 w:1)
	/// Proof: `ExternalValidators::ExternalValidators` (`max_values`: Some(1), `max_size`: Some(2002), added: 2497, mode: `MaxEncodedLen`)
	fn set_external_validators() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2_u64))
	}
	/// Storage: `ExternalValidators::CurrentEra` (r:1 w:1)
	/// Proof: `ExternalValidators::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::ErasStartSessionIndex` (r:1 w:1)
	/// Proof: `ExternalValidators::ErasStartSessionIndex` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::ForceEra` (r:1 w:0)
	/// Proof: `ExternalValidators::ForceEra` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::WhitelistedValidators` (r:1 w:0)
	/// Proof: `ExternalValidators::WhitelistedValidators` (`max_values`: Some(1), `max_size`: Some(2002), added: 2497, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::ExternalIndex` (r:1 w:0)
	/// Proof: `ExternalValidators::ExternalIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::SkipExternalValidators` (r:1 w:0)
	/// Proof: `ExternalValidators::SkipExternalValidators` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::ExternalValidators` (r:1 w:0)
	/// Proof: `ExternalValidators::ExternalValidators` (`max_values`: Some(1), `max_size`: Some(2002), added: 2497, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::PendingExternalIndex` (r:0 w:1)
	/// Proof: `ExternalValidators::PendingExternalIndex` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
	/// Storage: `ExternalValidators::WhitelistedValidatorsActiveEraPending` (r:0 w:1)
	/// Proof: `ExternalValidators::WhitelistedValidatorsActiveEraPending` (`max_values`: Some(1), `max_size`: Some(2002), added: 2497, mode: `MaxEncodedLen`)
	/// The range of component `r` is `[1, 100]`.
	fn new_session(r: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `249 + r * (20 ±0)`
		//  Estimated: `3487`
		// Minimum execution time: 15_000_000 picoseconds.
		Weight::from_parts(15_373_737, 3487)
			// Standard Error: 11_293
			.saturating_add(Weight::from_parts(126_262, 0).saturating_mul(r.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
}
