// Copyright 2025 DataHaven
// This file is part of DataHaven.

// DataHaven is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// DataHaven is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with DataHaven.  If not, see <http://www.gnu.org/licenses/>.

//! Autogenerated weights for `pallet_datahaven_native_transfer`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 36.0.0
//! DATE: 2025-01-27, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `datahaven-benchmarks`, CPU: `Apple M1 Pro`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("testnet-dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/release/datahaven-node
// benchmark
// pallet
// --chain=testnet-dev
// --steps=50
// --repeat=20
// --pallet=pallet_datahaven_native_transfer
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=pallets/datahaven-native-transfer/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_datahaven_native_transfer`.
pub trait WeightInfo {
    fn transfer_to_ethereum() -> Weight;
    fn pause() -> Weight;
    fn unpause() -> Weight;
}

/// Weights for `pallet_datahaven_native_transfer` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: `DataHavenNativeTransfer::Paused` (r:1 w:0)
    /// Proof: `DataHavenNativeTransfer::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:3 w:3)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `SnowbridgeOutboundQueue::MessageLeaves` (r:1 w:1)
    /// Proof: `SnowbridgeOutboundQueue::MessageLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `SnowbridgeOutboundQueue::Messages` (r:1 w:1)
    /// Proof: `SnowbridgeOutboundQueue::Messages` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `System::Number` (r:1 w:0)
    /// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::ExecutionPhase` (r:1 w:0)
    /// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
    /// Storage: `System::EventCount` (r:1 w:1)
    /// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Events` (r:1 w:1)
    /// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn transfer_to_ethereum() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `542`
        //  Estimated: `8799`
        // Minimum execution time: 91_234_000 picoseconds.
        Weight::from_parts(92_891_000, 8799)
            .saturating_add(T::DbWeight::get().reads(10_u64))
            .saturating_add(T::DbWeight::get().writes(7_u64))
    }
    
    /// Storage: `DataHavenNativeTransfer::Paused` (r:0 w:1)
    /// Proof: `DataHavenNativeTransfer::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `System::Number` (r:1 w:0)
    /// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::ExecutionPhase` (r:1 w:0)
    /// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
    /// Storage: `System::EventCount` (r:1 w:1)
    /// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Events` (r:1 w:1)
    /// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn pause() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `142`
        //  Estimated: `1627`
        // Minimum execution time: 8_123_000 picoseconds.
        Weight::from_parts(8_456_000, 1627)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    
    /// Storage: `DataHavenNativeTransfer::Paused` (r:0 w:1)
    /// Proof: `DataHavenNativeTransfer::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `System::Number` (r:1 w:0)
    /// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::ExecutionPhase` (r:1 w:0)
    /// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
    /// Storage: `System::EventCount` (r:1 w:1)
    /// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Events` (r:1 w:1)
    /// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn unpause() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `142`
        //  Estimated: `1627`
        // Minimum execution time: 8_234_000 picoseconds.
        Weight::from_parts(8_567_000, 1627)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

// For backwards compatibility and tests.
impl WeightInfo for () {
    /// Storage: `DataHavenNativeTransfer::Paused` (r:1 w:0)
    /// Proof: `DataHavenNativeTransfer::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `System::Account` (r:3 w:3)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `SnowbridgeOutboundQueue::MessageLeaves` (r:1 w:1)
    /// Proof: `SnowbridgeOutboundQueue::MessageLeaves` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `SnowbridgeOutboundQueue::Messages` (r:1 w:1)
    /// Proof: `SnowbridgeOutboundQueue::Messages` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `System::Number` (r:1 w:0)
    /// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::ExecutionPhase` (r:1 w:0)
    /// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
    /// Storage: `System::EventCount` (r:1 w:1)
    /// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Events` (r:1 w:1)
    /// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn transfer_to_ethereum() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `542`
        //  Estimated: `8799`
        // Minimum execution time: 91_234_000 picoseconds.
        Weight::from_parts(92_891_000, 8799)
            .saturating_add(RocksDbWeight::get().reads(10_u64))
            .saturating_add(RocksDbWeight::get().writes(7_u64))
    }
    
    /// Storage: `DataHavenNativeTransfer::Paused` (r:0 w:1)
    /// Proof: `DataHavenNativeTransfer::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `System::Number` (r:1 w:0)
    /// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::ExecutionPhase` (r:1 w:0)
    /// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
    /// Storage: `System::EventCount` (r:1 w:1)
    /// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Events` (r:1 w:1)
    /// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn pause() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `142`
        //  Estimated: `1627`
        // Minimum execution time: 8_123_000 picoseconds.
        Weight::from_parts(8_456_000, 1627)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    
    /// Storage: `DataHavenNativeTransfer::Paused` (r:0 w:1)
    /// Proof: `DataHavenNativeTransfer::Paused` (`max_values`: Some(1), `max_size`: Some(1), added: 496, mode: `MaxEncodedLen`)
    /// Storage: `System::Number` (r:1 w:0)
    /// Proof: `System::Number` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::ExecutionPhase` (r:1 w:0)
    /// Proof: `System::ExecutionPhase` (`max_values`: Some(1), `max_size`: Some(5), added: 500, mode: `MaxEncodedLen`)
    /// Storage: `System::EventCount` (r:1 w:1)
    /// Proof: `System::EventCount` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `System::Events` (r:1 w:1)
    /// Proof: `System::Events` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn unpause() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `142`
        //  Estimated: `1627`
        // Minimum execution time: 8_234_000 picoseconds.
        Weight::from_parts(8_567_000, 1627)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}