// Copyright 2025 DataHaven
// This file is part of DataHaven.

// DataHaven is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// DataHaven is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with DataHaven.  If not, see <http://www.gnu.org/licenses/>.


//! Autogenerated weights for `pallet_collective_treasury_council`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 51.0.0
//! DATE: 2026-01-08, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `ip-10-0-0-176`, CPU: `Intel(R) Xeon(R) Platinum 8375C CPU @ 2.90GHz`
//! WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/production/wbuild/datahaven-mainnet-runtime/datahaven_mainnet_runtime.compact.compressed.wasm
// --pallet
// pallet_collective_treasury_council
// --extrinsic
// 
// --header
// ../file_header.txt
// --template
// benchmarking/frame-weight-template.hbs
// --output
// runtime/mainnet/src/weights/pallet_collective_treasury_council.rs
// --steps
// 50
// --repeat
// 20

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for `pallet_collective_treasury_council`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_collective::WeightInfo for WeightInfo<T> {
	/// Storage: `TreasuryCouncil::Members` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:20 w:20)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Prime` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[0, 9]`.
	/// The range of component `n` is `[0, 9]`.
	/// The range of component `p` is `[0, 20]`.
	fn set_members(m: u32, _n: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0 + m * (425 ±0) + p * (206 ±0)`
		//  Estimated: `4117 + m * (266 ±4) + p * (2556 ±2)`
		// Minimum execution time: 10_890_000 picoseconds.
		Weight::from_parts(11_374_000, 4117)
			// Standard Error: 123_054
			.saturating_add(Weight::from_parts(3_648_585, 0).saturating_mul(m.into()))
			// Standard Error: 56_221
			.saturating_add(Weight::from_parts(4_823_866, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(p.into())))
			.saturating_add(T::DbWeight::get().writes(2_u64))
			.saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(p.into())))
			.saturating_add(Weight::from_parts(0, 266).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 2556).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TxPause::PausedCalls` (r:1 w:0)
	/// Proof: `TxPause::PausedCalls` (`max_values`: None, `max_size`: Some(532), added: 3007, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	fn execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `181 + m * (20 ±0)`
		//  Estimated: `3997 + m * (20 ±0)`
		// Minimum execution time: 23_609_000 picoseconds.
		Weight::from_parts(23_974_248, 3997)
			// Standard Error: 36
			.saturating_add(Weight::from_parts(1_488, 0).saturating_mul(b.into()))
			// Standard Error: 4_329
			.saturating_add(Weight::from_parts(49_040, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TxPause::PausedCalls` (r:1 w:0)
	/// Proof: `TxPause::PausedCalls` (`max_values`: None, `max_size`: Some(532), added: 3007, mode: `MaxEncodedLen`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[1, 9]`.
	fn propose_execute(b: u32, m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `181 + m * (20 ±0)`
		//  Estimated: `3997 + m * (20 ±0)`
		// Minimum execution time: 26_583_000 picoseconds.
		Weight::from_parts(27_577_760, 3997)
			// Standard Error: 59
			.saturating_add(Weight::from_parts(1_396, 0).saturating_mul(b.into()))
			// Standard Error: 7_112
			.saturating_add(Weight::from_parts(2_908, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(Weight::from_parts(0, 20).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalCount` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[2, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn propose_proposed(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127 + m * (20 ±0) + p * (55 ±0)`
		//  Estimated: `3548 + m * (27 ±0) + p * (54 ±0)`
		// Minimum execution time: 26_521_000 picoseconds.
		Weight::from_parts(24_546_964, 3548)
			// Standard Error: 123
			.saturating_add(Weight::from_parts(4_121, 0).saturating_mul(b.into()))
			// Standard Error: 16_844
			.saturating_add(Weight::from_parts(88_180, 0).saturating_mul(m.into()))
			// Standard Error: 6_461
			.saturating_add(Weight::from_parts(560_616, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
			.saturating_add(Weight::from_parts(0, 27).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 54).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[5, 9]`.
	fn vote(m: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `701 + m * (40 ±0)`
		//  Estimated: `4166 + m * (40 ±0)`
		// Minimum execution time: 26_832_000 picoseconds.
		Weight::from_parts(28_088_718, 4166)
			// Standard Error: 9_573
			.saturating_add(Weight::from_parts(29_121, 0).saturating_mul(m.into()))
			.saturating_add(T::DbWeight::get().reads(2_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
			.saturating_add(Weight::from_parts(0, 40).saturating_mul(m.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_early_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `234 + m * (40 ±0) + p * (55 ±0)`
		//  Estimated: `3696 + m * (43 ±0) + p * (55 ±0)`
		// Minimum execution time: 29_608_000 picoseconds.
		Weight::from_parts(31_151_416, 3696)
			// Standard Error: 11_127
			.saturating_add(Weight::from_parts(8_743, 0).saturating_mul(m.into()))
			// Standard Error: 3_156
			.saturating_add(Weight::from_parts(368_323, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 43).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TxPause::PausedCalls` (r:1 w:0)
	/// Proof: `TxPause::PausedCalls` (`max_values`: None, `max_size`: Some(532), added: 3007, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_early_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `225 + b * (1 ±0) + m * (40 ±0) + p * (78 ±0)`
		//  Estimated: `3997 + b * (1 ±0) + m * (29 ±1) + p * (74 ±0)`
		// Minimum execution time: 49_727_000 picoseconds.
		Weight::from_parts(52_632_323, 3997)
			// Standard Error: 119
			.saturating_add(Weight::from_parts(2_710, 0).saturating_mul(b.into()))
			// Standard Error: 6_206
			.saturating_add(Weight::from_parts(617_075, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(6_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 29).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 74).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Prime` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_disapproved(m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `284 + m * (33 ±0) + p * (55 ±0)`
		//  Estimated: `3747 + m * (34 ±0) + p * (56 ±0)`
		// Minimum execution time: 32_683_000 picoseconds.
		Weight::from_parts(33_618_365, 3747)
			// Standard Error: 11_326
			.saturating_add(Weight::from_parts(51_622, 0).saturating_mul(m.into()))
			// Standard Error: 3_213
			.saturating_add(Weight::from_parts(366_780, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(4_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 34).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 56).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Voting` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Members` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Members` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Prime` (r:1 w:0)
	/// Proof: `TreasuryCouncil::Prime` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SafeMode::EnteredUntil` (r:1 w:0)
	/// Proof: `SafeMode::EnteredUntil` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	/// Storage: `TxPause::PausedCalls` (r:1 w:0)
	/// Proof: `TxPause::PausedCalls` (`max_values`: None, `max_size`: Some(532), added: 3007, mode: `MaxEncodedLen`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// The range of component `b` is `[2, 1024]`.
	/// The range of component `m` is `[4, 9]`.
	/// The range of component `p` is `[1, 20]`.
	fn close_approved(b: u32, m: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `245 + b * (1 ±0) + m * (40 ±0) + p * (78 ±0)`
		//  Estimated: `3997 + b * (1 ±0) + m * (30 ±1) + p * (74 ±0)`
		// Minimum execution time: 52_698_000 picoseconds.
		Weight::from_parts(53_070_814, 3997)
			// Standard Error: 222
			.saturating_add(Weight::from_parts(3_274, 0).saturating_mul(b.into()))
			// Standard Error: 11_620
			.saturating_add(Weight::from_parts(652_161, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 1).saturating_mul(b.into()))
			.saturating_add(Weight::from_parts(0, 30).saturating_mul(m.into()))
			.saturating_add(Weight::from_parts(0, 74).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::ProposalOf` (r:0 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `p` is `[1, 20]`.
	fn disapprove_proposal(p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `293 + p * (32 ±0)`
		//  Estimated: `1778 + p * (32 ±0)`
		// Minimum execution time: 17_410_000 picoseconds.
		Weight::from_parts(17_765_646, 1778)
			// Standard Error: 1_773
			.saturating_add(Weight::from_parts(295_811, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 32).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:1)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::CostOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Proposals` (r:1 w:1)
	/// Proof: `TreasuryCouncil::Proposals` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::Voting` (r:0 w:1)
	/// Proof: `TreasuryCouncil::Voting` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// The range of component `d` is `[0, 1]`.
	/// The range of component `p` is `[1, 20]`.
	fn kill(d: u32, p: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `1347 + p * (55 ±0)`
		//  Estimated: `4814 + d * (5 ±1) + p * (55 ±0)`
		// Minimum execution time: 25_067_000 picoseconds.
		Weight::from_parts(27_967_968, 4814)
			// Standard Error: 4_430
			.saturating_add(Weight::from_parts(441_648, 0).saturating_mul(p.into()))
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(3_u64))
			.saturating_add(Weight::from_parts(0, 5).saturating_mul(d.into()))
			.saturating_add(Weight::from_parts(0, 55).saturating_mul(p.into()))
	}
	/// Storage: `TreasuryCouncil::ProposalOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::ProposalOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `TreasuryCouncil::CostOf` (r:1 w:0)
	/// Proof: `TreasuryCouncil::CostOf` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn release_proposal_cost() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `780`
		//  Estimated: `4245`
		// Minimum execution time: 16_390_000 picoseconds.
		Weight::from_parts(16_831_000, 4245)
			.saturating_add(T::DbWeight::get().reads(2_u64))
	}
}
